zajecia 2 :)
t0meck-pj/sop2021-22_24c pull request #12
Opened 2022-03-31 17:51 UTC by s24967-pj

2022-04-05 22:42 UTC, t0meck-pj requested changes
Zadania zrobione ładnie. Opisy też przeważnie dobre. Drobne błędy ale podałem co należy poprawić. Kilka drastycznych błędów ale też zaznaczonych.

Natomiast instalacja debiana... Musisz ją znacznie poprawić. Podać w wielu miejscach uzasadnienia swoich decyzji. Pokazać, że decyzja nie jest bezmyślna tylko przemyślana i miałaś podstawy by taką decyzję podjąć.
Tam gdzie uzasadnienie było i nie dodałem komentarza jest ok.

Natomiast póki nie poprawisz powyższych błędów nie mogę tego zaakceptować.

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie1.txt
> +nadajemy uprawnienia -> chmod 777 cwiczenie1
Ej ej ej! https://media4.giphy.com/media/l2JdXb24Kwipp5nIQ/200w.gif
Nie uważałaś na moim wykładzie z UKOS na poprzednim semestrze!

A teraz wyjaśnienie:
https://pimylifeup.com/chmod-777/

I ode mnie wyjaśnienie na podstawie analogii do sytuacji bardziej życiowej:
Wyobraź sobie, że masz napisaną pracę dyplomową i tak ustawione uprawnienia.
- Dowolny użytkownik na systemie może to przeczytać i oddać jako swoją pracę i będziesz miała problem z plagiatem.
- Dowolny użytkownik na systemie może Tobie tę pracę usunąć - i szczerze mówiąc jest to najmniej problematyczny przypadek bo przecież masz kopię bezpieczeństwa prawda? Przywrócisz i po problemie.
- Dowolny użytkownik na systemie potencjalnie może zmienić Tobie tę pracę i powiedzmy wpisać tam bluzgi, obelgi itd... Teraz wyobraź sobie swoje zażenowanie kiedy promotor będzie to czytał. A Ty nawet nie będziesz wiedziała, że ktoś zrobił zmianę.

W taki sam sposób jak 3 działają wirusy. Zmieniają kod dodając kawałki kodu szkodliwego do czegoś co potem będzie uruchomione i będzie szkodzić. Uruchamiać koparki bitcoinów albo robiąc z Twojego komputera część sieci botnet używanej do ataków hackerskich.
Nigdy ale to NIGDY nie należy nadawać takich uprawnień bez całkowitej świadomości co się w ten sposób robi!


Nie chcę byś czuła się, że Cię tu karcę czy coś. Nie. Tylko byś naprawdę dobrze zrozumiała znaczenie tej linijki i nigdy więcej tego błędu nie popełniła. Podejście psychologiczne do tematu percepcji mówi, że jeśli połączy się wiedzę z emocjami to dobrze się to zapamiętuje. Dlatego kiedy występuje silna emocja to wiedza jej towarzysząca jest dobrze zapamiętana. Także widzisz nawet i tu jest uzasadnienie tego co robię (to w kontekście opisu instalacji debiana i wymogu podawania wszędzie uzasadnienia)

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie2.txt
> +nadajemy uprawnienia -> chmod 777 cwiczenie2.sh
Tu już nie będę się powtarzał. Wiesz o co chodzi.

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie3.txt
> +PS1 - to, to co pokazuje się na początku w command line \u@\h:\w\$. \u-username \h-hostname \w-pełna ścieżka folderu w którym obecnie się znajdujemy
Przydała by się informacja co z tym możemy fajnego zrobić. Kiedy ma sens zmiana tej wartości by coś fajnego uzyskać i nie chodzi mi o kolorki. Na ostatnich zajęciach mówiłem o możliwości wywołania funkcji i git prompt.

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie3.txt
> +USER - wypisuje nazwę obecnego użytkownika
Kiedy poniższe 3 zmienne mogą być przydatne?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie4.txt
> +zmieniamy uprawnienie -> chmod 777 cwiczenie4.sh
I jeszcze jeden i jeszcze raz...

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie4.txt
> +printf "$X\n"
Nie tak się używa printf-a. Poniżej masz link do wyjaśnienia:
https://linuxize.com/post/bash-printf-command/

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie4.txt
> +różnica między echo a printf - obydwa służą do wypisywania danych w konsoli. Echo jest szybsze, ale nie ma takich możliwości formatowania jak printf. Printf może przyjąćtylko jeden argument, a echo w
printf przyjmuje dynamiczną ilość argumentów tylko trzeba umieć tego użyć.
https://linuxize.com/post/bash-printf-command/
Składnia printf jest bardzo podobna do tej z języka C.

Jeśli jakieś polecenie zwraca inną wartość niż `0` to znaczy, że zakończyło się z błędem a numer informuje jaki to błąd był. Sprawdź proszę jeszcze raz jaką wartość otrzymujesz. Kod wyjścia ostatniego polecenia możesz uzyskać przez `echo $?` ale musi ono być wykonane bezpośrednio po wywołaniu printf.

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie5b.txt
> +3. Zadanie na SOP, cwiczenie 5b SOP -> obydwa SOP wyświetlane na zielono
Wspaniale

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +3. Wybieramy typ pliku z wirtualnym dyskiem:
No a jaka wartość została wybrana i dlaczego?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +4. Wybieramy czy chcemy stały rozmiar, czy dysk dynamicznie przydzielany. Przy stałym rozmiarze tworzy od razu plik o rozmiarze przez nas wybranym, nie ważne ile miejsca zajmują dane w środku VM. Dys
Jaki typ alokacji i rozmiar dysku zostały wybrane oraz dlaczego

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +5. Po wybraniu wszystkich ustawień uruchamiamy maszynę, do wyboru mamy 3 opcje:
Kiedy należy używać każdej z nich?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +1. Wybór dysku startowego – wybieramy plik z systemem operacyjnym, który chcemy zainstalować na WM. (w tym przypadku wybieramy ściągnięty plik iso)
Nie z systemem tylko z instalatorem systemu

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +- Install (ustawianie wszystkiego tekstowo w konsoli)
Czym poza prezentacją procesu instalacji różni się instalacja graficzna oraz tekstowa?
Kiedy należy której używać?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +3. Ustawianie języka w jakim będzie przebiegał proces instalacji oraz język w zainstalowanym już systemie (w moim przypadku English)
Dobrze. Dlaczego?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +5. Wybieramy system kodowania znaków
Jaki i dlaczego?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +6. Konfiguracja klawiatury, czyli ustawienia klawiatur, w tym przypadku wybranie Polskiego, jeżeli chcemy mieć polskie literki.
Czyli, że wybrany był polski układ klawiatury czy nie?
Zastanów się także dlaczego możesz celowo nie chcieć używać języka polskiego.

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +- Guided – use entire disk and set up LVM (Tak samo jak w poprzednim, tylko z wbudowanym mechanizmem systemu operacyjnego do zarządzania przestrzenią pamięci masowej)
Mało. 
Zasady: Kiedy należy a kiedy nie używać LVM?
Co to de facto jest?
Jakie są zalety/wady tego mechanizmu?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +10. Wybór dysku, który chcemy podzielić, schemat partycjonowania dysku (wszystkie pliki w jednej partycji, podzielone /home (główne)  /var (zmienne) /tmp (tymczasowe)) (wybieramy jedną partycję)
- Kiedy należy wydzielać poszczególne katalogi na osobne partycje?
- Co to daje?
- Jakie katalogi powinny być wydzielone?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +11. Podsumowanie naszych partycji, między innymi wypisana jest jej nazwa oraz to ile miejsca zajmuje.
Rozpisz proszę docelowy układ partycji.
- Jakie typy partycji zostały użyte?
- Czym się od siebie różnią?
- Kiedy należy który używać tudzież do czego należy, który używać?
- Jakie rozmiary mają partycje?
- Jakie są dostępne systemy plików oraz ich charakterystyka (wydajność, bezpieczeństwo, kompatybilność, kiedy którego używać)
- Jakie systemy plików zostały wybrane i dlaczego?
- Jakie zostały użyte punkty montowania?
- Jakie flagi zostały ustawione w szczególności flaga bootująca?
  - Co ona oznacza?
  - Do czego się ją stosuje?
  - Gdzie i kiedy należy ją ustawić?
  - Czy może być ich więcej czy tylko jedna? Dlaczego?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +12. Znalezienie i wybór lokalizacji skąd będzie korzystane z archiwum debiana (Poland -> deb.debian.org)
Dobrze. Dlaczego?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +14. Software selection –jakie środowisko graficzne chcemy zainstalować  (zostawiam 1, 2 i ostatnie) Tutaj z tego co mi się wydaje wybór jest zależny po prostu od preferencji :D
Nie do końca. Preferencje to jedna składowa ale czynnikami są:
- kompatybilność - Twoja aplikacja, która będzie chodziła na danym systemie działa tylko pod konkretnymi środowiskami graficznymi i dlatego wybierasz właśnie takie a nie inne
- wydajność - niektóre są bardziej wydajne od innych ale kosztem ergonomii. Które?
- ergonomia - czy dane środowisko jest wygodne w użyciu czy nie koniecznie. Są takie, które są zaprojektowane źle... na pierwszy rzut oka
- ograniczenia sprzętowe - masz stary komputer i nie masz wymaganych zasobów albo klient nie zgodził się płacić za droższy sprzęt tylko dlatego by działało na niej lepsze środowisko graficzne
- element wizualny - żeby wyglądało ładnie
- bezpieczeństwo - środowiska graficzne są napisane w różny sposób. Niektóre mogą nie wspierać dodatkowych mechanizmów bezpieczeństwa przez co są niebezpieczne. Lub same tworzą luki bezpieczeństwa przez to jak zostały zaimplementowane i np. serwer graficzny ma zbyt duże uprawnienia więc potencjalny atakujący może zrobić bardzo dużo.
- a czy środowisko graficzne jest potrzebne w pierwszej kolejności?
  - dlaczego nie należy instalować środowiska graficznego?

Wszystko to składa się na podjęcie decyzji. Musisz uzasadnić swoją decyzję.

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +- Standard system utilities – podstawowe narzędzia
- Co to jest?
- Czy bez tego da się zainstalować system?
- Czy będzie on działał dobrze czy nie?
- A będzie się wtedy dało z niego normalnie korzystać czy nie?

2022-04-05 22:42 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia1/instalacja_debian_linux.txt.txt
> +15. Install the GRUB boot loader – wybieramy TAK (GRUB bootloader umożliwia nam wybór uruchamianego systemu operacyjnego) oraz gdzie ma zostać on zainstalowany, czy chcemy wpisać miejsce samemu czzai
- Czy są alternatywy dla GRUB-a?
- Czy można uruchomić system bez bootloadera?
- Gdzie można zainstalować bootloader w obrębie jednego dysku twardego? (podpowiem: są 2 miejsca - MBR i BR - kiedy gdzie należy instalować? )

2022-05-13 16:49 UTC, s24967-pj commented
Dzień dobry, wysłałam commita z poprawionymi zadaniami i zastosowanymi uwagami.

2022-05-18 19:39 UTC, t0meck-pj approved these changes
Bity uprawnień masz do poprawienia troszkę ale jest znacznie lepiej niż było.
Instalacja debiana... nie odniosłaś się do wszystkich moich komentarzy ale chyba już pozostawimy to w tej formie.

2022-05-18 19:39 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie1.txt
> +nadajemy uprawnienia -> chmod 644 cwiczenie1
Znacznie lepiej ale faktycznie tutaj właściciel czyli Ty możesz mieć nadany bit wykonywalności czyli 744 bo inaczej nie uruchomisz skryptu w opisany sposób.

2022-05-18 19:39 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie2.txt
> +nadajemy uprawnienia -> chmod 644 cwiczenie2.sh
744

2022-05-18 19:39 UTC, t0meck-pj commented on s24967-DariaSzablowska/zajecia2/cwiczenie4.txt
> +zmieniamy uprawnienie -> chmod 644 cwiczenie4.sh
744

2022-05-18 19:39 UTC, merged